### ISSUE TITLE
Error in link in Readme

### ISSUE THREAD

**Issue by EionRobb** [wasmer-examples/wordpress-wasmer-starter#2]
The readme has a link to 
> Live example: https://wordpress-wasmer-examples.wasmer.app/

but it redirects to
`http://wordpress-wasmer-examples.wasmer.apphttp/localhost/`
which is an invalid TLD

**Comment by syrusakbary** [comment]
I believe this issue is already fixed. Does the issue still happen for you @EionRobb?
